FROM mcr.microsoft.com/devcontainers/python:3.9

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && sudo ./aws/install \
    && rm -rf awscliv2.zip ./aws

# Set up working directory
WORKDIR /workspace
